#pragma once

#include "audio/ofxICTranscriptionClient.h"
#include "audio/ofxICTranscriptionTypes.h"
#include "segmentation/ofxICSegmentationClient.h"
#include "segmentation/ofxICSegmentationTypes.h"
#include "chat/ofxICChatSession.h"
#include "chat/ofxICChatTypes.h"
#include "documents/ofxICDocumentIndex.h"
#include "endpoint/ofxICEndpoint.h"
#include "media/ofxICMediaClient.h"
#include "media/ofxICMediaTypes.h"
#include "music/ofxICAceStepMusicClient.h"
#include "music/ofxICAceStepMusicTypes.h"
#include "music/ofxICStabilityAudioClient.h"
#include "music/ofxICStabilityAudioTypes.h"
#include "tools/ofxICToolLoop.h"
#include "tools/ofxICToolRegistry.h"
